version: 0.2

phases:
  install:
    commands:
      - echo Entering the install phase...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started
      - mvn install
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed

reports:
  reportGroupCucumberJson:
    files:
      - 'Cucumber_DataDrivenWithExcelFile-main/target/cucumber-tests.xml'
    discard-paths: yes
    file-format: CUCUMBERJSON
artifacts:
  files:
    - target/classes
  discard-paths: yes
