ersion: 0.2

phases:
  install:
    commands:
      - echo Entering the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y junit
      - apt-get install -y testng
      - apt-get install wget
      - apt-get install -y unzip xvfb libxi6 libgconf-2-4
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
      - echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - apt-get -y update
      - apt-get -y install google-chrome-stable
      
      - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      
      - mv chromedriver /usr/bin/chromedriver
      - chown root:root /usr/bin/chromedriver
      - chmod +x /usr/bin/chromedriver
      
      - wget https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started
      - mvn clean
      - mvn test
      - ls 
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed

# reports:
#   reportGroupCucumberJson:
#     files:
#       - 'Cucumber_DataDrivenWithExcelFile-main/target/cucumber-tests.xml'
#     discard-paths: yes
#     file-format: CUCUMBERJSON
# artifacts:
#   files:
#     - target/classes
#   discard-paths: yes
